name: Go Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, 386]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.1'

      - name: Build
        run: |
          GOOS=linux GOARCH=${{ matrix.goarch }} go build -o light-linux-${{ matrix.goarch }} ./

      - name: Get Release
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const releases = await github.rest.repos.listReleases({
              owner,
              repo,
            });
            const release = releases.data.find(r => r.tag_name === context.ref.substring(10)); // Remove "refs/tags/" prefix
            if (release) {
              core.setOutput('upload_url', release.upload_url);
            } else {
              core.setFailed('Release not found');
            }

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./light-linux-${{ matrix.goarch }}
          asset_name: light-linux-${{ matrix.goarch }}
          asset_content_type: application/octet-stream

  build-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, 386]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.1'

      - name: Build
        run: |
          GOOS=windows GOARCH=${{ matrix.goarch }} go build -o light-windows-${{ matrix.goarch }}.exe ./

      - name: Get Release
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const releases = await github.rest.repos.listReleases({
              owner,
              repo,
            });
            const release = releases.data.find(r => r.tag_name === context.ref.substring(10)); // Remove "refs/tags/" prefix
            if (release) {
              core.setOutput('upload_url', release.upload_url);
            } else {
              core.setFailed('Release not found');
            }

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./light-windows-${{ matrix.goarch }}.exe
          asset_name: light-windows-${{ matrix.goarch }}.exe
          asset_content_type: application/octet-stream
